version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_HOST=localhost
      - MARIADB_ROOT_PASSWORD=hello_root
      - MARIADB_DATABASE=order_form
    networks:
      - order-network

  api:
    build: ./
    container_name: node_api
    volumes:
      - ./:/order-api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    command: bash -c "cd /order-api && yarn start"
    networks:
      - order-network
    depends_on:
      - mariadb
  
  web:
    image: node:14.20.0
    container_name: node_web
    volumes:
      - ../order:/order
    ports:
      - "8080:8080"
    command: bash -c "cd /order && npm run serve"
    networks:
      - order-network
    
networks:
  order-network: